"""
Shared indicator threshold constants used by BasicStrategy and BasicAndLLMStrategy.

Centralised here so any threshold change is applied to both strategies
automatically.
"""

MOMENTUM_THRESHOLD = 0.002
RSI_LONG_BLOCK = 80
RSI_SHORT_BLOCK = 20
BB_LONG_BLOCK = 95
BB_SHORT_BLOCK = 5
RSI_BULLISH_THRESHOLD = 40
RSI_BEARISH_THRESHOLD = 60
BB_BULLISH_THRESHOLD = 30
BB_BEARISH_THRESHOLD = 70
STOCH_BULLISH_THRESHOLD = 20
STOCH_BEARISH_THRESHOLD = 80
WILLIAMS_BULLISH_THRESHOLD = -80
WILLIAMS_BEARISH_THRESHOLD = -20
MIN_INDICATORS_FOR_SIGNAL = 5
MIN_CONSENSUS_VOTES = 1
BASE_CONFIDENCE_CAP = 0.50
MOMENTUM_ATR_MULTIPLIER = 1.0
INDICATOR_VOTE_WEIGHT = 0.05
MIN_INDICATOR_BONUS = -0.20
MAX_INDICATOR_BONUS = 0.40
ATR_VOLATILITY_THRESHOLD_PCT = 1.0
ATR_PENALTY_PER_EXTRA_PCT = 0.05
MAX_ATR_PENALTY = 0.10
MIN_CONFIDENCE = 0.10
MAX_CONFIDENCE = 0.95
MIN_ACTIONABLE_CONFIDENCE = 0.20
POSITION_SIZING_PROPOSAL = 0.20
MIN_DYNAMIC_POSITION_SIZE = 0.05
MAX_DYNAMIC_POSITION_SIZE = 0.25
